# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BinarySear.ch
email: cian.ruane9@mail.dcu.ie
description: > # this means to ignore newlines until "baseurl:"
  Student of CPSSD in DCU, competitive programmer, former Google SRE intern. 
  Do you ever buy a cool domain and then feel obligated to actually do
  something with it? That's this. I'm planning to post updates on projects,
  competitions, and general software dev life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://binarysear.ch" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CianLR
github_username:  CianLR

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - build.sh
